name: flutter_dynamic_icon
description: Flutter plugin to change the app launcher icon dynamically.
version: 2.1.0
publish_to: 'none'

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.codelessly.flutter_dynamic_icon
        pluginClass: FlutterDynamicIconPlugin
      ios:
        pluginClass: FlutterDynamicIconPlugin
